### ISSUE TITLE
C++ 不支持变量长度数组，请不要误导新人

### ISSUE THREAD

**Issue by guyutongxue** [fightingwangzq/cpp-learning#4]
您好。偶然看到您的这一仓库，发现您的 [C++数组长度可以为变量吗？](https://mp.weixin.qq.com/s/rR6YhNdZDLQ2TADfDzWP3Q) 文章中提出了错误的观点。我在这里郑重地告知您：**C++ 不支持变量长度数组（VLA）**。

简单来说，VLA 是 C 语言的语法，于 1999 年在 C99 标准中引入（并在 2011 年的 C11 中又取消）。但 C++ 直至目前不支持任何 VLA 相关语法。容易引起误会的是，GCC 和 Clang++ 编译器提供了包含 VLA 的**GNU 扩展语法**，并且默认引入这些扩展。因此，VLA 在这些 C++ 编译器下可行。反之，如果关闭这些扩展（通过添加 `-pedantic-errors` 选项）或者非 GNU 兼容的编译器（如 MSVC），则 VLA 不可用。

## 实例测试

[GCC 在严格模式下禁止 C++ VLA](https://gcc.godbolt.org/z/1exqYY1cx)
[Clang++ 在严格模式下禁止 C++ VLA](https://gcc.godbolt.org/z/hbec5jh7a)
[MSVC 在任何情形下都不允许 C++ VLA](https://gcc.godbolt.org/z/35EYM7EMG)

## 标准文本

> In a declaration `T` `D` where `D` has the form
> 
>> `D1` `[` *constant-expression* <sub>opt</sub> `]` *attribute-specifier-seq* <sub>opt</sub>
> 
> and the type of the contained *declarator-id* in the declaration `T` `D1` is “derived-declarator-type-list `T`”, the type of the *declarator-id* in `D` is “derived-declarator-type-list array of `N` `T`”. The *constant-expression* shall be a converted **constant expression** of type `std​::​size_­t` (\[expr.const\]). Its value `N` specifies the array bound, i.e., the number of elements in the array; `N` shall be greater than zero.

取自 C++ 最新标准草案 [[dcl.array] 第一段](https://eel.is/c++draft/dcl.array#1)。

其中，注意加粗的文本：（上述语法形式方括号内的）*constant-expression* 需要是一个经转换后类型为 `std::size_t` 的**常量表达式**。

**Comment by chengxumiaodaren** [comment]
嗯好的，谢谢你的issue。
标准是不支持的，这是属于GCC的扩展，公众号文章不能修改，我其他平台的文章应该有提到。
已修正链接。
